Repository nix-community/NixOS-WSL, pull requests merged in 2022-11, with the labels that each got.

#151 Fix eval by disabling module completely when wsl.enable = false
  modules/wsl-distro.nix
Labels: bug

#153 wsl.conf: proper option types
  flake.nix
  modules/wsl-conf.nix
  modules/wsl-distro.nix
Labels: enhancement

#140 Fix syschdemd exit code
  modules/wsl-distro.nix
  scripts/syschdemd.nix
  scripts/syschdemd.sh
Labels: bug, hacktoberfest-accepted

#161 Add CI Tests
  .editorconfig
  .github/workflows/main.yml
  .github/workflows/release.yml
  .vscode/launch.json
  checks/nixpkgs-fmt.nix
  checks/shfmt.nix
  checks/side-effects.nix
  flake.nix
  modules/build-tarball.nix
  modules/installer.nix
  scripts/syschdemd.nix
  scripts/syschdemd.sh
  scripts/wrapper.sh
  tests/README.md
  tests/basic-functionality.Tests.ps1
  tests/docker/docker-native.nix
  tests/docker/docker.Tests.ps1
  tests/exit-codes.Tests.ps1
  tests/lib/Dockerfile
  tests/lib/lib.ps1
  tests/shells.Tests.ps1
  tests/systemd-user.Tests.ps1
Labels: enhancement

#160 Disable powerManagement
  modules/wsl-distro.nix
Labels: enhancement

#159 Disable timesynced
  modules/wsl-distro.nix
Labels: enhancement
