Repository nix-community/NixOS-WSL, pull requests merged in 2022-10, with the labels that each got.

#144 Do not import minimal profile by default
  configuration.nix
Labels: bug

#145 remove boot.isContainer
  modules/wsl-distro.nix
Labels: bug, hacktoberfest-accepted

#134 feat: native systemd support
  .gitignore
  .vscode/settings.json
  configuration.nix
  flake.nix
  modules/installer.nix
  modules/interop.nix
  modules/wsl-distro.nix
  scripts/native-systemd-shim/Cargo.lock
  scripts/native-systemd-shim/Cargo.toml
  scripts/native-systemd-shim/shim.nix
  scripts/native-systemd-shim/src/main.rs
Labels: enhancement

#147 NixOS users.users.<user> attribute name and .name can differ
  .vscode/settings.json
  modules/wsl-distro.nix
  scripts/syschdemd.nix
  scripts/syschdemd.sh
Labels: enhancement, hacktoberfest-accepted
