Repository nix-community/NixOS-WSL, pull requests merged in 2022-07, with the labels that each got.

#103 Make resolve settings easier overwritable
  modules/wsl-distro.nix
Labels: enhancement

#116 Fix dead link
  README.md
Labels: documentation

#90 fix docker-desktop systemd proxy
  modules/docker-desktop.nix
Labels: bug

#115 prevent systemd-tmpfiles from removing the xorg socket
  modules/wsl-distro.nix
Labels: bug

#119 interop: move to its own module and disable re-registration by default
  flake.nix
  modules/interop.nix
  modules/wsl-distro.nix
Labels: bug
