Repository nix-community/NixOS-WSL, pull requests merged in 2023-07, with the labels that each got.

#260 Allow customizing the system config to include in the tarball
  modules/build-tarball.nix
Labels: enhancement

#267 fix: getent missing in syschdemd
  flake.lock
  scripts/syschdemd.nix
Labels: bug

#272 Update flakes
  flake.lock
Labels: release-exclude
