Repository nix-community/NixOS-WSL, pull requests merged in 2024-10, with the labels that each got.

#561 shell-wrapper: wrap /bin/sh
  modules/systemd/native/wrap-shell.nix
  modules/wsl-distro.nix
Labels: bug

#560 wslConf: convert to freeform type
  modules/wsl-conf.nix
Labels: enhancement

#543 docs: add certificate install instructions
  docs/src/SUMMARY.md
  docs/src/how-to/install-msixbundle-certificate.md
Labels: documentation
